/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpaca.scrapping.jw;

import org.testng.Assert;
import org.testng.annotations.Test;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		Assert.assertEquals("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
