/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpaca.scrapping.jw;

import alpaca.scrapping.jw.engine.CoreEngineDeux;
import alpaca.scrapping.jw.factory.BuilderSupervisor;
import alpaca.scrapping.jw.selections.ContentTypeSelection;
import alpaca.scrapping.jw.selections.CountrySelection;
import alpaca.scrapping.jw.selections.ProviderSelection;

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {

		String releaseYearFrom;
		String releaseYearUntil;

		releaseYearFrom = "2020";
		releaseYearUntil = "2020";

		BuilderSupervisor builderSupervisor = new BuilderSupervisor();

		builderSupervisor.getRequestBuilder().setCountry(CountrySelection.INDIA.getCountrySelection());
		builderSupervisor.getRequestBuilder()
				.setContentMovieOrShow(ContentTypeSelection.MOVIE.getContentTypeSelection());

		builderSupervisor.getProviderBuilder().appendProvider(ProviderSelection.AMAZONPRIME);
		builderSupervisor.getRequestBuilder().setProviders(builderSupervisor.getProviderBuilder().getProvidersArray());

		builderSupervisor.getRequestBuilder().setReleaseYearFrom(releaseYearFrom);
		builderSupervisor.getRequestBuilder().setReleaseYearUntil(releaseYearUntil);

		String requestEndpoint = builderSupervisor.getRequestBuilder().getRequestEndpoint();

		CoreEngineDeux coreEngineDeux = new CoreEngineDeux();
		coreEngineDeux.scrapeData(requestEndpoint);

	}
}
